site_name: Neural Circuit Extraction Framework
site_description: Documentation for the Neural Circuit Extraction and Modular Composition Framework
site_author: ARC AGI Team

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/yourusername/simplest_arc_agi
repo_name: yourusername/simplest_arc_agi

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Overview: overview.md
  - Components:
    - Data Generation: components/data_generation.md
    - Transformer Architecture: components/transformer_architecture.md
    - Training Pipeline: components/training_pipeline.md
    - Scalability: components/scalability.md
    - Circuit Database: components/circuit_database.md
    - Explanation & Interpretability: components/explanation.md
    - Modular Composition: components/modular_composition.md
  - Implementation Roadmap: roadmap.md
  - ARC Evaluation Protocol: arc_evaluation.md
  - Future Directions: future_directions.md
  - API Reference:
    - Data Generation: api/data_generation.md
    - Models: api/models.md
    - Training: api/training.md
    - Database: api/database.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    - Training a Model: tutorials/training.md
    - Extracting Circuits: tutorials/extraction.md
    - Composing Circuits: tutorials/composition.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/simplest_arc_agi
